#num - Номер в таблице
#name - Имя в таблице
#Rname - Русское название
#Lname - Латинское название
#Ename - Английское название
#Birth - Дата открытия
#Eshell - Электронная оболочка
#Doxi - Степень окисления
#Amass - Атомная масса
#density - Плотность
#Tmelting - Температура плавления
#boil - Температура кипения

elements_1 = {
    "H":{
        'num':1,
        'name':'H',
        'Rname':'Водород',
        'Lname':'Hydrogenium',
        'Ename':'Hydrogen',
        'Birth':1766,
        'Eshell':'K1',
        'Doxi':'-1,+1',
        'Amass': '1.00794',
        'density':'0.0000899',
        'Tmelting':'-259',
        'boil':'-252',
        'link':'pic/element_1.jpg'
    },

    "He":{
        'num':2,
        'name':'He',
        'Rname':'Гелий',
        'Lname':'Helium',
        'Ename':'Helium',
        'Birth':1895,
        'Eshell':'K2',
        'Doxi':'0',
        'Amass': '4.002602',
        'density':'0.00017846',
        'Tmelting':'-272',
        'boil':'-268',
        'link':'pic/element_2.jpg'
    },

    "Li":{
        'num':3,
        'name':'Li',
        'Rname':'Литий',
        'Lname':'Lithium',
        'Ename':'Lithium',
        'Birth':1817,
        'Eshell':'K2 L1',
        'Doxi':'-1,+1',
        'Amass':'6.941',
        'density':'0.534',
        'Tmelting':'+180',
        'boil':'+1342',
        'link':'pic/element_3.jpg'
    },

    "Be": {
        'num':4,
        'name':'Be',
        'Rname':'Берилий',
        'Lname':'Beryllium',
        'Ename':'Beryllium',
        'Birth':1797,
        'Eshell':'K2 L2',
        'Doxi':'+2',
        'Amass':'9.012182',
        'density':'1.848',
        'Tmelting':'+1278',
        'boil':'+2970',
        'link':'pic/element_4.jpg'
    },

    "B": {
        'num':5,
        'name':'B',
        'Rname':'Бор',
        'Lname':'Borum',
        'Ename':'Boron',
        'Birth':1808,
        'Eshell':'K2 L3',
        'Doxi':'+3',
        'Amass':'10.811',
        'density':'2.34',
        'Tmelting':'+2075',
        'boil':'+3865',
        'link':'pic/element_5.jpg'
    },

    "C": {
        'num':6,
        'name':'C',
        'Rname':'Углерод',
        'Lname':'Carbonium',
        'Ename':'Carbon',
        'Birth':'Неизвестно',
        'Eshell':'K2 L4',
        'Doxi':'-4,+2,+4',
        'Amass':'12.0107',
        'density':'2.26',
        'Tmelting':'+3550',
        'boil':'+4027',
        'link':'pic/element_6.jpg'
    },

    "N": {
        'num':7,
        'name':'N',
        'Rname':'Азот',
        'Lname':'Nitrogenium',
        'Ename':'Nitrogen',
        'Birth':1772,
        'Eshell':'K2 L5',
        'Doxi':'-3,-2,-1,+1,+2,+3,+4,+5',
        'Amass': '14.0067',
        'density':'0.001251',
        'Tmelting':'-209',
        'boil':'-195',
        'link':'pic/element_7.jpg'
    },

    "O": {
        'num':8,
        'name':'O',
        'Rname':'Кислород',
        'Lname':'Oxigenium',
        'Ename':'Oxygen',
        'Birth':1774,
        'Eshell':'K2 L6',
        'Doxi':'-2,-1,+1,+2',
        'Amass':'15.9994',
        'density':'0.00142897',
        'Tmelting':'-218',
        'boil':'-182',
        'link':'pic/element_8.jpg'
    },

    "F": {
        'num':9,
        'name':'F',
        'Rname':'Фтор',
        'Lname':'Fluorum',
        'Ename':'Fluorine',
        'Birth':1886,
        'Eshell':'K2 L7',
        'Doxi':'-1',
        'Amass':'9.012182',
        'density':'1.848',
        'Tmelting':'+1278',
        'boil':'+2970',
        'link':'pic/element_9.jpg'
    },

    "Ne": {
        'num':10,
        'name':'Ne',
        'Rname':'Неон',
        'Lname':'Neon',
        'Ename':'Neon',
        'Birth':1898,
        'Eshell':'K2 L8',
        'Doxi':'0',
        'Amass':'20.1797',
        'density':'0.0009002',
        'Tmelting':'-248',
        'boil':'-246',
        'link':'pic/element_10.jpg'
    },

    "Na": {
        'num':11,
        'name':'Na',
        'Rname':'Натрий',
        'Lname':'Natrium',
        'Ename':'Sodium',
        'Birth':1807,
        'Eshell':'K2 L8 M1',
        'Doxi':'+1',
        'Amass':'22.98976928',
        'density':'0.971',
        'Tmelting':'+98',
        'boil':'+882',
        'link':'pic/element_11.jpg'
    },

    "Mg": {
        'num':12,
        'name':'Mg',
        'Rname':'Магний',
        'Lname':'Magnesium',
        'Ename':'Magnesium',
        'Birth':1755,
        'Eshell':'K2 L8 M2',
        'Doxi':'+2',
        'Amass':'24.3050',
        'density':'1.738',
        'Tmelting':'+650',
        'boil':'+1090',
        'link':'pic/element_12.jpg',
    },

    "Al": {
        'num':13,
        'name':'Al',
        'Rname':'Алюминий',
        'Lname':'Aluminium',
        'Ename':'Aluminium',
        'Birth':1825,
        'Eshell':'K2 L8 M3',
        'Doxi':'+3',
        'Amass':'26.9815386',
        'density':'2.6989',
        'Tmelting':'+660',
        'boil':'+2518',
        'link':'pic/element_13.jpg'
    },

    "Si": {
        'num':14,
        'name':'Si',
        'Rname':'Кремний',
        'Lname':'Silicium',
        'Ename':'Silicon',
        'Birth':1823,
        'Eshell':'K2 L8 M4',
        'Doxi':'-4,+2,+4',
        'Amass':'28.0855',
        'density':'2.33',
        'Tmelting':'+1414',
        'boil':'+2349',
        'link':'pic/element_14.jpg'
    },

    "P": {
        'num':15,
        'name':'P',
        'Rname':'Фосфор',
        'Lname':'Phosphorus',
        'Ename':'Phosphorus',
        'Birth':1669,
        'Eshell':'K2 L8 M5',
        'Doxi':'-3,+3,+4,+5',
        'Amass':'30.973762',
        'density':'1.82',
        'Tmelting':'+44',
        'boil':'+279',
        'link':'pic/element_15.jpg'
    },

    "S": {
        'num':16,
        'name':'S',
        'Rname':'Сера',
        'Lname':'Sulfur',
        'Ename':'Sulfur',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M6',
        'Doxi':'-2,+2,+4,+6',
        'Amass':'32.065',
        'density':'2.070',
        'Tmelting':'+112',
        'boil':'+444',
        'link':'pic/element_16.jpg'
    },

    "Cl": {
        'num':17,
        'name':'Cl',
        'Rname':'Хлор',
        'Lname':'Clorum',
        'Ename':'Chlorine',
        'Birth':1774,
        'Eshell':'K2 L8 M7',
        'Doxi':'-1,+1,+3,+5,+7',
        'Amass':'35.453',
        'density':'0.003214',
        'Tmelting':'-100',
        'boil':'-34',
        'link':'pic/element_17.jpg'
    },

    "Ar": {
        'num':18,
        'name':'Ar',
        'Rname':'Аргон',
        'Lname':'Argon',
        'Ename':'Argon',
        'Birth':1894,
        'Eshell':'K2 L8 M8',
        'Doxi':'0',
        'Amass':'39.948',
        'density':'0.001784',
        'Tmelting':'-189',
        'boil':'-185',
        'link':'pic/element_18.jpg'
    },

    "K": {
        'num':19,
        'name':'K',
        'Rname':'Калий',
        'Lname':'Kalium',
        'Ename':'Potassium',
        'Birth':1807,
        'Eshell':'K2 L8 M8 N1',
        'Doxi':'+1',
        'Amass':'39.0983',
        'density':'0.856',
        'Tmelting':'+63',
        'boil':'+773',
        'link':'pic/element_19.jpg'
    },

    "Ca": {
        'num':20,
        'name':'Ca',
        'Rname':'Кальций',
        'Lname':'Calcium',
        'Ename':'Calcium',
        'Birth':1808,
        'Eshell':'K2 L8 M8 N2',
        'Doxi':'+2',
        'Amass':'40.078',
        'density':'1.55',
        'Tmelting':'+838',
        'boil':'+1483',
        'link':'pic/element_20.jpg'
    },

    "Sc": {
        'num':21,
        'name':'Sc',
        'Rname':'Скандий',
        'Lname':'Scandium',
        'Ename':'Scandium',
        'Birth':1879,
        'Eshell':'K2 L8 M9 N2',
        'Doxi':'+3',
        'Amass':'44.955912',
        'density':'2.99',
        'Tmelting':'+1539',
        'boil':'+2835',
        'link':'pic/element_21.jpg'
    },

    "Ti": {
        'num':22,
        'name':'Ti',
        'Rname':'Титан',
        'Lname':'Titanium',
        'Ename':'Titanium',
        'Birth':1791,
        'Eshell':'K2 L8 M10 N2',
        'Doxi':'+2,+3,+4',
        'Amass':'47.867',
        'density':'4.54',
        'Tmelting':'+1660',
        'boil':'+3285',
        'link':'pic/element_22.jpg'
    },

    "Va": {
        'num':23,
        'name':'V',
        'Rname':'Ванадиум',
        'Lname':'Vanadium',
        'Ename':'Vanadium',
        'Birth':1801,
        'Eshell':'K2 L8 M11 N2',
        'Doxi':'+2,+3,+4,+5',
        'Amass':'50.9415',
        'density':'6.11',
        'Tmelting':'+1887',
        'boil':'+3377',
        'link':'pic/element_23.jpg'
    },

    "Cr": {
        'num':24,
        'name':'Cr',
        'Rname':'Хром',
        'Lname':'Chromium',
        'Ename':'Chromium',
        'Birth':1797,
        'Eshell':'K2 L8 M12 N2',
        'Doxi':'-2,+2,+3,+4,+6',
        'Amass':'51.9961',
        'density':'7.19',
        'Tmelting':'+1855',
        'boil':'+2670',
        'link':'pic/element_24.jpg'
    },

    "Mn": {
        'num':25,
        'name':'Mn',
        'Rname':'Марганец',
        'Lname':'Manganum',
        'Ename':'Manganese',
        'Birth':1774,
        'Eshell':'K2 L8 M13 N2',
        'Doxi':'-1,+2,+3,+4,+5,+6,+7',
        'Amass':'54.938045',
        'density':'7.21',
        'Tmelting':'+1242',
        'boil':'+1960',
        'link':'pic/element_25.jpg'
    },

    "Fe": {
        'num':26,
        'name':'Fe',
        'Rname':'Железо',
        'Lname':'Ferrum',
        'Ename':'Iron',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M14 N2',
        'Doxi':'-2,+2,+3',
        'Amass':'55.845',
        'density':'7.88',
        'Tmelting':'+1538',
        'boil':'+2859',
        'link':'pic/element_26.jpg'
    },

    "Co": {
        'num':27,
        'name':'Co',
        'Rname':'Кобальт',
        'Lname':'Cobaltum',
        'Ename':'Cobalt',
        'Birth':1735,
        'Eshell':'K2 L8 M15 N2',
        'Doxi':'-1,+2,+3',
        'Amass':'58.933195',
        'density':'8.9',
        'Tmelting':'+1493',
        'boil':'+2868',
        'link':'pic/element_27.jpg'
    },

    "Ni": {
        'num':28,
        'name':'Ni',
        'Rname':'Никель',
        'Lname':'Niccolum',
        'Ename':'Nickel',
        'Birth':1751,
        'Eshell':'K2 L8 M16 N2',
        'Doxi':'-1,+2,+3',
        'Amass':'58.6934',
        'density':'8.902',
        'Tmelting':'+1453',
        'boil':'+2732',
        'link':'pic/element_28.jpg'
    },

    "Cu": {
        'num':29,
        'name':'Cu',
        'Rname':'Медь',
        'Lname':'Cuprum',
        'Ename':'Copper',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M18 N1',
        'Doxi':'+1,+2',
        'Amass':'63.546',
        'density':'8.92',
        'Tmelting':'+1083',
        'boil':'+2565',
        'link':'pic/element_29.jpg'
    },

    "Zn": {
        'num':30,
        'name':'Zn',
        'Rname':'Цинк',
        'Lname':'Zincum',
        'Ename':'Zinc',
        'Birth':1500,
        'Eshell':'K2 L8 M18 N2',
        'Doxi':'+2',
        'Amass':'65.409',
        'density':'7.133',
        'Tmelting':'+419',
        'boil':'+906',
        'link':'pic/element_30.jpg'
    },

    "Ga": {
        'num':31,
        'name':'Ga',
        'Rname':'Галлий',
        'Lname':'Gallium',
        'Ename':'Gallium',
        'Birth':1875,
        'Eshell':'K2 L8 M18 N3',
        'Doxi':'+3',
        'Amass':'69.723',
        'density':'5.91',
        'Tmelting':'+29',
        'boil':'+2202',
        'link':'pic/element_31.jpg'
    },

    "Ge": {
        'num':32,
        'name':'Ge',
        'Rname':'Германий',
        'Lname':'Germanium',
        'Ename':'Germanium',
        'Birth':1886,
        'Eshell':'K2 L8 M18 N4',
        'Doxi':'+2,+4',
        'Amass':'72.64',
        'density':'5.323',
        'Tmelting':'+935',
        'boil':'+2828',
        'link':'pic/element_32.jpg'
    },

    "As": {
        'num':33,
        'name':'As',
        'Rname':'Мышьяк',
        'Lname':'Arsenicum',
        'Ename':'Arsenic',
        'Birth':1250,
        'Eshell':'K2 L8 M18 N5',
        'Doxi':'-3,+3,+4',
        'Amass':'74.92160',
        'density':'5.72',
        'Tmelting':'+817',
        'boil':'+613',
        'link':'pic/element_33.jpg'
    },

    "Se": {
        'num':34,
        'name':'Se',
        'Rname':'Селен',
        'Lname':'Selenium',
        'Ename':'Selenium',
        'Birth':1817,
        'Eshell':'K2 L8 M18 N16',
        'Doxi':'-2,+2,+4,+6',
        'Amass':'78.96',
        'density':'4.79',
        'Tmelting':'+215',
        'boil':'+683',
        'link':'pic/element_34.jpg'
    },

    "Br": {
        'num':35,
        'name':'Br',
        'Rname':'Бром',
        'Lname':'Bromum',
        'Ename':'Bromine',
        'Birth':1826,
        'Eshell':'K2 L8 M18 N7',
        'Doxi':'-1,+1,+3,+5,+7',
        'Amass':'79.904',
        'density':'3.14',
        'Tmelting':'-7',
        'boil':'+58',
        'link':'pic/element_35.jpg'
    },

    "Kr": {
        'num':36,
        'name':'Kr',
        'Rname':'Криптон',
        'Lname':'Krypton',
        'Ename':'Krypton',
        'Birth':1898,
        'Eshell':'K2 L2 M18 N8',
        'Doxi':'0,+2,+4',
        'Amass':'83.978',
        'density':'0.003749',
        'Tmelting':'-156',
        'boil':'-152',
        'link':'pic/element_36.jpg'
    },

    "Rb": {
        'num':37,
        'name':'Rb',
        'Rname':'Рубидий',
        'Lname':'Rubidium',
        'Ename':'Rubidium',
        'Birth':1861,
        'Eshell':'K2 L8 M18 N8 O1',
        'Doxi':'+1',
        'Amass':'85.4678',
        'density':'1.53',
        'Tmelting':'+39',
        'boil':'+688',
        'link':'pic/element_37.jpg'
    },

    "Sr": {
        'num':38,
        'name':'Sr',
        'Rname':'Стронций',
        'Lname':'Stroncium',
        'Ename':'Stroncium',
        'Birth':1790,
        'Eshell':'K2 L8 M18 N8 O2',
        'Doxi':'+2',
        'Amass':'87.62',
        'density':'2.54',
        'Tmelting':'+767',
        'boil':'+1382',
        'link':'pic/element_38.jpg'
    },

    "Y": {
        'num':39,
        'name':'Y',
        'Rname':'Иттрий',
        'Lname':'Yttrium',
        'Ename':'Yttrium',
        'Birth':1794,
        'Eshell':'K2 L2 M18 N9 O2',
        'Doxi':'+3',
        'Amass':'88.90585',
        'density':'4.47',
        'Tmelting':'+1523',
        'boil':'+3337',
        'link':'pic/element_39.jpg'
    },

    "Zr": {
        'num':40,
        'name':'Zr',
        'Rname':'Цирконий',
        'Lname':'Zirconium',
        'Ename':'Zirconium',
        'Birth':1789,
        'Eshell':'K2 L8 M18 N10 O2',
        'Doxi':'+3,+4',
        'Amass':'91.224',
        'density':'6.51',
        'Tmelting':'+1852',
        'boil':'+4377',
        'link':'pic/element_40.jpg'
    },

    "Nb": {
        'num':41,
        'name':'Nb',
        'Rname':'Ниобий',
        'Lname':'Niobium',
        'Ename':'Niobium',
        'Birth':1801,
        'Eshell':'K2 L8 M18 N12 O1',
        'Doxi':'-1,+3,+5',
        'Amass':'92.90638',
        'density':'8.58',
        'Tmelting':'+2468',
        'boil':'+4742',
        'link':'pic/element_41.jpg'
    },

    "Mo": {
        'num':42,
        'name':'Mo',
        'Rname':'Молибден',
        'Lname':'Molybdaenum',
        'Ename':'Molybdenum',
        'Birth':1781,
        'Eshell':'K2 L8 M18 N13 O1',
        'Doxi':'-2,+2,+3,+4,+5,+6',
        'Amass':'95.94',
        'density':'10.22',
        'Tmelting':'+2617',
        'boil':'+4610',
        'link':'pic/element_42.jpg'
    },

    "Tc": {
        'num':43,
        'name':'Tc',
        'Rname':'Технеций',
        'Lname':'Technetium',
        'Ename':'Technetium',
        'Birth':1937,
        'Eshell':'K2 L8 M18 N13 O2',
        'Doxi':'+1,+4,+7',
        'Amass':'98.9063',
        'density':'11.49',
        'Tmelting':'+2157',
        'boil':'+4265',
        
    },

    "Ru": {
        'num':44,
        'name':'Ru',
        'Rname':'Рутений',
        'Lname':'Ruthenium',
        'Ename':'Ruthenium',
        'Birth':1844,
        'Eshell':'K2 L8 M18 N15 O1',
        'Doxi':'-2,+2,+4,+6,+8',
        'Amass':'101.7',
        'density':'12.41',
        'Tmelting':'+2337',
        'boil':'+4077',
        'link':'pic/element_44.jpg'
    },

    "Rh": {
        'num':45,
        'name':'Rh',
        'Rname':'Родий',
        'Lname':'Rhodium',
        'Ename':'Rhodium',
        'Birth':1803,
        'Eshell':'K2 L8 M18 N16 O1',
        'Doxi':'-1,+2,+3,+4',
        'Amass':'102.90550',
        'density':'12.41',
        'Tmelting':'+1966',
        'boil':'+3727',
        'link':'pic/element_45.jpg'
    },

    "Rd": {
        'num':46,
        'name':'Pd',
        'Rname':'Палладий',
        'Lname':'Palladium',
        'Ename':'Palladium',
        'Birth':1803,
        'Eshell':'K2 L2 M18 N18',
        'Doxi':'+2,+4',
        'Amass':'406.42',
        'density':'12.02',
        'Tmelting':'+1552',
        'boil':'+2665',
        'link':'pic/element_46.jpg'
    },

    "Ag": {
        'num':47,
        'name':'Ag',
        'Rname':'Серебро',
        'Lname':'Argentum',
        'Ename':'Silver',
        'Birth':'Неизвестно',
        'Eshell':'K2 L2 M18 N18 O1',
        'Doxi':'+1,+2',
        'Amass':'107.8682',
        'density':'10.49',
        'Tmelting':'+961.9',
        'boil':'+2162',
        'link':'pic/element_47.jpg'
    },

    "Cd": {
        'num':48,
        'name':'Cd',
        'Rname':'Кадмий',
        'Lname':'Cadmium',
        'Ename':'Cadmium',
        'Birth':1877,
        'Eshell':'K2 L2 M18 N18 O2',
        'Doxi':'+2',
        'Amass':'112.411',
        'density':'8.64',
        'Tmelting':'+319',
        'boil':'+765',
        'link':'pic/element_48.jpg'
    },

    "In": {
        'num':49,
        'name':'In',
        'Rname':'Индий',
        'Lname':'Indium',
        'Ename':'Indium',
        'Birth':1863,
        'Eshell':'K2 L8 M18 N18 O3',
        'Doxi':'+3',
        'Amass':'114.818',
        'density':'7.31',
        'Tmelting':'+156',
        'boil':'+2080',
        'link':'pic/element_49.jpg'
    },

    "Sn": {
        'num':50,
        'name':'Sn',
        'Rname':'Олово',
        'Lname':'Stannum',
        'Ename':'Tin',
        'Birth':'Неизвестно',
        'Eshell':'K2 L2 M18 N18 O4',
        'Doxi':'+2,+4',
        'Amass':'118.710',
        'density':'7.29',
        'Tmelting':'+232',
        'boil':'+2598',
        'link':'pic/element_50.jpg'
    },

    "Sb": {
        'num':51,
        'name':'Sb',
        'Rname':'Сурьма',
        'Lname':'Stibium',
        'Ename':'Antimony',
        'Birth':'Неизвестно',
        'Eshell':'K2 L2 M18 N18 O5',
        'Doxi':'-3,+3,+5',
        'Amass':'121.760',
        'density':'6.69',
        'Tmelting':'+630',
        'boil':'+1633',
        'link':'pic/element_51.jpg'
    },

    "Te": {
        'num':52,
        'name':'Te',
        'Rname':'Теллур',
        'Lname':'Tellurium',
        'Ename':'Tellurium',
        'Birth':1783,
        'Eshell':'K2 L8 M18 N18 O6',
        'Doxi':'-2,+2,+4,+6',
        'Amass':'127.60',
        'density':'6.25',
        'Tmelting':'+449',
        'boil':'+990',
        'link':'pic/element_52.jpg'
    },

    "I": {
        'num':53,
        'name':'I',
        'Rname':'Йод',
        'Lname':'Iodium',
        'Ename':'Iodine',
        'Birth':1811,
        'Eshell':'K2.L8 M18 N18 O7',
        'Doxi':'-1,+1,+5,+7',
        'Amass':'16.90447',
        'density':'4.94',
        'Tmelting':'+113',
        'boil':'+184',
        'link':'pic/element_53.jpg'
    },

    "Xe": {
        'num':54,
        'name':'Xe',
        'Rname':'Ксенон',
        'Lname':'Xenon',
        'Ename':'Xenon',
        'Birth':1898,
        'Eshell':'K2 L8 M18 N18 O8',
        'Doxi':'0,+2,+4,+6,+8',
        'Amass':'113.293',
        'density':'0.005894',
        'Tmelting':'-112',
        'boil':'-107',
        'link':'pic/element_54.jpg'
    },

    "Cs": {
        'num':55,
        'name':'Cs',
        'Rname':'Цезий',
        'Lname':'Caesium',
        'Ename':'Caesium',
        'Birth':1860,
        'Eshell':'K2 L8 M18 N18 O8 P1',
        'Doxi':'+1',
        'Amass':'132.905',
        'density':'1.9',
        'Tmelting':'+28',
        'boil':'+690',
        'link':'pic/element_55.jpg'
    },

    "Ba": {
        'num':56,
        'name':'Ba',
        'Rname':'Барий',
        'Lname':'Barium',
        'Ename':'Barium',
        'Birth':1808,
        'Eshell':'K2 L8 M18 N18 O8 P2',
        'Doxi':'+2',
        'Amass':'137.327',
        'density':'3.5',
        'Tmelting':'+725',
        'boil':'+1640',
        'link':'pic/element_56.jpg'
    },

    "La": {
        'num':57,
        'name':'La',
        'Rname':'Лантан',
        'Lname':'Lanthanum',
        'Ename':'Lanthanum',
        'Birth':1839,
        'Eshell':'K2 L8 M18 N18 O9 P2',
        'Doxi':'+2',
        'Amass':'138.509',
        'density':'6.16',
        'Tmelting':'+950',
        'boil':'+3456',
        'link':'pic/element_57.jpg'
    },

    "Ce": {
        'num':58,
        'name':'Ce',
        'Rname':'Церий',
        'Lname':'Cerium',
        'Ename':'Cerium',
        'Birth':1803,
        'Eshell':'K2 L8 M18 N19 O9 P2',
        'Doxi':'3,+4',
        'Amass':'140.116',
        'density':'6.77',
        'Tmelting':'+798',
        'boil':'+3443',
        'link':'pic/element_58.jpg'
    },

    "Pr": {
        'num':59,
        'name':'Pr',
        'Rname':'Празеодим',
        'Lname':'Praseodymium',
        'Ename':'Praseodymium',
        'Birth':1885,
        'Eshell':'K2 L8 M18 N21 O8 P2',
        'Doxi':'+3',
        'Amass':'140.904',
        'density':'6.773',
        'Tmelting':'+931',
        'boil':'+3290',
        'link':'pic/element_59.jpg'
    },

    "Nd": {
        'num':60,
        'name':'Nd',
        'Rname':'Неодим',
        'Lname':'Neodymium',
        'Ename':'Neodymium',
        'Birth':1885,
        'Eshell':'K2 L2 M18 N22 O8 P2',
        'Doxi':'+3',
        'Amass':'144.242',
        'density':'7',
        'Tmelting':'+1010',
        'boil':'+3066',
        'link':'pic/element_60.jpg'
    },

    "Pm": {
        'num':61,
        'name':'Pm',
        'Rname':'Прометий',
        'Lname':'Promethium',
        'Ename':'Promethi',
        'Birth':1945,
        'Eshell':'K2 L8 M18 N23 O8 P2',
        'Doxi':'+2,+3',
        'Amass':'146.915',
        'density':'7.2',
        'Tmelting':'+1166',
        'boil':'+2998',
        'link':'pic/element_61.jpg'
    },

    "Sm": {
        'num':62,
        'name':'Sm',
        'Rname':'Самарий',
        'Lname':'Samarium',
        'Ename':'Samarium',
        'Birth':1879,
        'Eshell':'K2 L8 M18 N24 O8 P2',
        'Doxi':'+2,+3',
        'Amass':'150.36',
        'density':'7.54',
        'Tmelting':'+1072',
        'boil':'+1778',
        'link':'pic/element_62.jpg'
    },

    "Eu": {
        'num':63,
        'name':'Eu',
        'Rname':'Европий',
        'Lname':'Europium',
        'Ename':'Europium',
        'Birth':1901,
        'Eshell':'K2 L8 M18 N25 O8 P2',
        'Doxi':'+2,+3',
        'Amass':'151.964 ',
        'density':'5.25',
        'Tmelting':'+822',
        'boil':'+1597',
        'link':'pic/element_63.jpg'
    },
    "Gd": {
        'num':64,
        'name':'Gd',
        'Rname':'Гадолиний',
        'Lname':'Gadolinium',
        'Ename':'Gadolinium',
        'Birth':1880,
        'Eshell':'K2 L2 M18 N25 O9 P2',
        'Doxi':'+3,+4',
        'Amass':' 157.25',
        'density':'7.89 ',
        'Tmelting':'+1311',
        'boil':'+3264',
        'link':'pic/element_64.jpg'
    },

    "Tb": {
        'num':65,
        'name':'Tb',
        'Rname':'Тербий',
        'Lname':'Terbium',
        'Ename':'Terbium',
        'Birth': 1843,
        'Eshell':'K2 L8 M18 N27 O8 P2',
        'Doxi':'+3',
        'Amass':'158.925',
        'density':'8.25',
        'Tmelting':'+1360',
        'boil':'+3021',
        'link':'pic/element_65.jpg'
    },

    "Dy": {
        'num':66,
        'name':'Dy',
        'Rname':'Диспрозий',
        'Lname':'Dysprosium',
        'Ename':'Dysprosium',
        'Birth':1886,
        'Eshell':'K2 L8 M18 N28 O8 P2',
        'Doxi':'+3',
        'Amass':'162.5',
        'density':'8.56',
        'Tmelting':'+1409',
        'boil':'+2560',
        'link':'pic/element_66.jpg'
    },

    "Ho": {
        'num':67,
        'name':'Ho',
        'Rname':'Гольмий',
        'Lname':'Holmium',
        'Ename':'Holmium',
        'Birth':1878,
        'Eshell':'K2 L2 M18 N29 O8 P2',
        'Doxi':'+3',
        'Amass':'+164.930',
        'density':'8.78',
        'Tmelting':'+1470',
        'boil':'+2693',
        'link':'pic/element_67.jpg'
    },

    "Er": {
        'num':68,
        'name':'Er',
        'Rname':'Эрбий',
        'Lname':'Erbium',
        'Ename':'Erbium',
        'Birth':1842,
        'Eshell':'K2 L8 M18 N30 O8 P2',
        'Doxi':'+2,+3',
        'Amass':'167.259',
        'density':'9.05',
        'Tmelting':'+1522',
        'boil':'+2861',
        'link':'pic/element_68.jpg'
    },

    "Tm": {
        'num':69,
          'name':'Tm',
          'Rname':'Тулий',
          'Lname':'Thulium',
          'Ename':'Thulium',
          'Birth':1879,
          'Eshell':'K2 L8 M18 N31 O8 P2',
          'Doxi':'+2,+3',
          'Amass':'168.934',
          'density':'9.32',
          'Tmelting':'+1545',
          'boil':'+1945',
          'link':'pic/element_69.jpg'
    },

    "Yb": {
        'num': 70,
        'name':'Yb',
        'Rname':'Иттербий',
        'Lname':'Ytterbium',
        'Ename':'Yterrbium',
        'Birth':1878 ,
        'Eshell':'K2 L8 M18 N32 O8 P2',
        'Doxi':'+3',
        'Amass':'173.04',
        'density':'6.97',
        'Tmelting':'+824',
        'boil':'+1193',
        'link':'pic/element_70.jpg'
    },

    "Lu": {
        'num':71,
        'name':'Lu',
        'Rname':'Лутенций',
        'Lname':'Lutetium',
        'Ename':'Lutetium',
        'Birth':1907,
        'Eshell':'K2 L8 M18 N32 O9 P2',
        'Doxi':'+3',
        'Amass':'174.967',
        'density':'9.84',
        'Tmelting':'+1656',
        'boil':'+3393',
        'link':'pic/element_70.jpg'
    },

    "Hf": {
        'num':72,
        'name':'Hf',
        'Rname':'Гафний',
        'Lname':'Hafnium',
        'Ename':'Hafnium',
        'Birth':1923,
        'Eshell':'K2 L8 M18 N32 O10 P2',
        'Doxi':'+4',
        'Amass':'178.49',
        'density':'13.31',
        'Tmelting':'+2233',
        'boil':'+4603',
        'link':'pic/element_72.jpg'
    },

    "Ta": {
        'num':73,
        'name':'Ta',
        'Rname':'Тантал',
        'Lname':'Tantalum',
        'Ename':'Tantalum',
        'Birth':1802,
        'Eshell':'K2 L8 M18 N32 O11 P2',
        'Doxi':'+5',
        'Amass':'180.948',
        'density':'16.68',
        'Tmelting':'+3017',
        'boil':'+5458',
        'link':'pic/element_73.jpg'
    },

    "W": {
        'num':74,
        'name':'W',
        'Rname':'Вольфрам',
        'Lname':'Wolframium',
        'Ename':'Tungsten',
        'Birth':1783,
        'Eshell':'K2 L8 M18 N32 O12 P2',
        'Doxi':'-2,-1,+2,+3,+4,+5,+6',
        'Amass':'183.84',
        'density':'19.26',
        'Tmelting':'+3407',
        'boil':'+5555',
        'link':'pic/element_74.jpg'
    },

    "Re": {
        'num':75,
        'name':'Re',
        'Rname':'Рений',
        'Lname':'Rhenium',
        'Ename':'Rhenium',
        'Birth':1925,
        'Eshell':'K2 L8 M18 N32 O13 P2',
        'Doxi':'-1,+2,+4,+6,+7',
        'Amass':'186.207',
        'density':'21.03',
        'Tmelting':'+3180',
        'boil':'+5596'
    },

    "Os": {
        'num':76 ,
        'name':'Os',
        'Rname':'Осмий',
        'Lname':'Osmium',
        'Ename':'Osmium',
        'Birth':1804,
        'Eshell':'K2 L8 M18 N32 O14 P2',
        'Doxi':'-2,+2,+3,+4,+6,+8',
        'Amass':'190.23',
        'density':'22.61',
        'Tmelting':'+3405',
        'boil':'+5027'
    },

    "Ir": {
        'num': 77,
        'name':'Ir',
        'Rname':'Иридий ',
        'Lname':'Iridium ',
        'Ename':'Iridium ',
        'Birth':1803,
        'Eshell':'K2 L8 M18 N32 O15 P2',
        'Doxi':'-1,+1,+2,+3,+4,+6',
        'Amass':'192.217',
        'density':'22.65',
        'Tmelting':'+2410',
        'boil':'+4428',
        'link':'pic/element_77.jpg'
    },

    "Pt": {
        'num':78,
        'name':'Pt',
        'Rname':'Платина',
        'Lname':'Platinum',
        'Ename':'Platinum',
        'Birth':1735,
        'Eshell':'K2 L8 M18 N32 O17 P1',
        'Doxi':'+2,+4',
        'Amass':'195.084',
        'density':'21.45',
        'Tmelting':'+1772',
        'boil':'+3827',
        'link':'pic/element_78.jpg'
    },

    "Au": {
        'num':79,
        'name':'Au',
        'Rname':'Золото',
        'Lname':'Aurum',
        'Ename':'Gold',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M18 N32 O18 P1',
        'Doxi':'+1,+3',
        'Amass':'196.966',
        'density':'19.32',
        'Tmelting':'+1064',
        'boil':'+2856',
        'link':'pic/element_79.jpg'
    },

    "Hg": {
        'num':80,
        'name':'Hg',
        'Rname':'Ртуть',
        'Lname':'Hydragyrum',
        'Ename':'Mercury',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M18 N32 O18 P2',
        'Doxi':'+1,+2',
        'Amass':'200.59',
        'density':'13.5',
        'Tmelting':'-39',
        'boil':'+356',
        'link':'pic/element_80.jpg'
    },


    "Tl": {
        'num':81,
        'name':'Tl',
        'Rname':'Таллий',
        'Lname':'Thallium',
        'Ename':'Thallium',
        'Birth':1861,
        'Eshell':'K2 L8 M18 N32 O18 P3',
        'Doxi':'+1,+3',
        'Amass':'204.383',
        'density':'11.85',
        'Tmelting':'+303',
        'boil':'+1473',
        'link':'pic/element_81.jpg'
    },

    "Pb": {
        'num':82,
        'name':'Pb',
        'Rname':'Свинец',
        'Lname':'Plumbum',
        'Ename':'Lead',
        'Birth':'Неизвестно',
        'Eshell':'K2 L8 M18 N',
        'Doxi':'+2,+4',
        'Amass':'207.2',
        'density':'11.34',
        'Tmelting':'+327',
        'boil':'+1740',
        'link':'pic/element_82.jpg'
    },

    "Bi": {
        'num':83,
        'name':'Bi',
        'Rname':'Висмут',
        'Lname':'Bismutum',
        'Ename':'Bismuth',
        'Birth':1400,
        'Eshell':'K2 L8 M18 N32 O18 P5',
        'Doxi':'+3,+5',
        'Amass':'208.98',
        'density':'9.8',
        'Tmelting':'+271',
        'boil':'+1560',
        'link':'pic/element_83.jpg'
    },
    "Po" : {'num':84,
          'name':'Po',
          'Rname':'Полоний',
          'Lname':'Polonium',
          'Ename':'Polonium',
          'Birth':1898,
          'Eshell':'K2 L8 M18 N32 O18 P6',
          'Doxi':'+2,+4',
          'Amass':'208.982',
          'Density':'9.2',
          'Tmelting':'+254',
          'boil':'+962' },

"At" : {'num':85,
         'name':'At',
         'Rname':'Астат',
         'Lname':'Astatium',
         'Ename':'Astatine',
         'Birth':1940,
         'Eshell':'K2 L8 M18 N32 O18 P7',
         'Doxi':'-1,+1,+3,+5,+7',
         'Amass':'209.987',
         'density':'6.4',
         'Tmelting':'+230',
         'boil':'+302',
         'link':'pic/element_85.jpg'
          },

"Rn" : {'num':86,
         'name':'Rn',
         'Rname':'Радон',
         'Lname':'Radon',
         'Ename':'Radon',
         'Birth':1900,
         'Eshell':'K2 L8 M18 N32 O18 P8',
         'Doxi':'0,+2',
         'Amass':'222.017',
         'density':'9.81',
         'Tmelting':'-71',
         'boil':'-62'
          },

"Fr" : {'num':87,
         'name':'Fr',
         'Rname':'Франций',
         'Lname':'Francium',
         'Ename':'Francium',
         'Birth':1939,
         'Eshell':'K2 L8 M18 N32 O18 P8 Q1',
         'Doxi':'+1',
         'Amass':'223.019',
         'density':'1.87',
         'Tmelting':'+20',
         'boil':'+650' 
         },

"Ra": {'num':88,
         'name':'Ra',
         'Rname':'Радий',
         'Lname':'Radium',
         'Ename':'Radium',
         'Birth':1898,
         'Eshell':'K2 L8 M18 N32 O18 P8 Q2',
         'Doxi':'+2',
         'Amass':'226.025',
         'density':'5.55',
         'Tmelting':'+958',
         'boil':'+1735' },

"Ac" : {'num':89,
         'name':'Ac',
         'Rname':'Актиний',
         'Lname':'Actinium',
         'Ename':'Actinium',
         'Birth':1899,
         'Eshell':'K2 L8 M18 N32 O18 P9 Q2',
         'Doxi':'+3',
         'Amass':'227.027',
         'density':'10.07',
         'Tmelting':'+1047',
         'boil':'+3197'},

"Th" : {'num':90,
         'name':'Th',
         'Rname':'Торий',
         'Lname':'Thorium',
         'Ename':'Thorium',
         'Birth':1828,
         'Eshell':'K2 L8 M18 N32 O18 P10 Q2',
         'Doxi':'+4',
         'Amass':'232.038',
         'density':'11.72',
         'Tmelting':'+1750',
         'boil':'+4787'},

"Pa" : {'num':91,
         'name':'Pa',
         'Rname':'Протактиний',
         'Lname':'Protactinium',
         'Ename':'Protactinium',
         'Birth':1913,
         'Eshell':'K2 L8 M18 N32 O20 P9 Q2',
         'Doxi':'+4,+5',
         'Amass':'231.035',
         'density':'15.37',
         'Tmelting':'+1840',
         'boil':'+4030' },

"U": {'num':92,
         'name':'U',
         'Rname':'Уран',
         'Lname':'Uranium',
         'Ename':'Uranium',
         'Birth':1789,
         'Eshell':'K2 L8 M18 N32 O21 P9 Q2',
         'Doxi':'+3,+4,+5,+6',
         'Amass':'238.028',
         'density':'19.05',
         'Tmelting':'+1132',
         'boil':'+3743',
         'link':'pic/element_92.jpg'
           },

"Np" : {'num':93,
         'name':'Np',
         'Rname':'Нептуний',
         'Lname':'Neptunium',
         'Ename':'Neptunium',
         'Birth':1940,
         'Eshell':'K2 L8 M18 N32 O22 P9 Q2',
         'Doxi':'+3,+4,+5,+5',
         'Amass':'237.048',
         'density':'20.48',
         'Tmelting':'+640',
         'boil':'+3900' },
    
"Pu" : {'num':94,
         'name':'Pu',
         'Rname':'Плутоний',
         'Lname':'Plutonium',
         'Ename':'Plutonium',
         'Birth':1940,
         'Eshell':'K2 L8 M18 N32 O24 P8 Q2',
         'Doxi':'+3,+4,+5,+6',
         'Amass':'244.064',
         'density':'19.74',
         'Tmelting':'+641',
         'boil':'+3235',
         'link':'pic/element_94.jpg'
         },

"Am" : {'num':95,
         'name':'Am',
         'Rname':'Амерций',
         'Lname':'Amercium',
         'Ename':'Amercium',
         'Birth':1944,
         'Eshell':'K2 L8 M18 N32 O25 P8 Q2',
         'Doxi':'+3,+4,+5,+6',
         'Amass':'243.061',
         'density':'13.67',
         'Tmelting':'+1176',
         'boil':'+2607',
         'link':'pic/element_95.jpg'
          },

"Cm" : {'num':96,
         'name':'Cm',
         'Rname':'Кюрий',
         'Lname':'Curium',
         'Ename':'Curium',
         'Birth':1944,
         'Eshell':'K2 L8 M18 N32 O25 P9 Q2',
         'Doxi':'+3,+4',
         'Amass':'247.070',
         'density':'13.51',
         'Tmelting':'+1340',
         'boil':'+3108' },

"Bk" : {'num':97,
         'name':'Bk',
         'Rname':'Берклий',
         'Lname':'Berklium',
         'Ename':'Berklium',
         'Birth':1949,
         'Eshell':'K2 L8 M18 N32 O27 P8 Q2',
         'Doxi':'+3,+4',
         'Amass':'247.070',
         'density':'13.25',
         'Tmelting':'+986',
         'boil':'+2625' },

"Cf" : {'num':98,
         'name':'Cf',
         'Rname':'Калифорний',
         'Lname':'Californium',
         'Ename':'Californium',
         'Birth':1950,
         'Eshell':'K2 L8 M18 N32 O28 P8 Q2',
         'Doxi':'+3,+4',
         'Amass':'251.079',
         'density':'15.1',
         'Tmelting':'+900',
         'boil':'+1470' },

"Es" : {'num':99,
         'name':'Es',
         'Rname':'Эйнштейний',
         'Lname':'Einsteinium',
         'Ename':'Ensteinium',
         'Birth':1952,
         'Eshell':'K2 L8 M18 N32 O29 P8 Q2',
         'Doxi':'+3',
         'Amass':'252.082',
         'density':'13.5',
         'Tmelting':'+860',
         'boil':'Неизвестно' },

"Fm" : {'num':100,
         'name':'Fm',
         'Rname':'Фермий',
         'Lname':'Fermium',
         'Ename':'Fermium',
         'Birth':1952,
         'Eshell':'K2 L8 M18 N32 O30 P8 Q2',
         'Doxi':'+3',
         'Amass':'257.095',
         'density':'Неизвестно',
         'Tmelting':'+1525',
         'boil':'Неизвестно' },

"Md" : {'num':101,
         'name':'Md',
         'Rname':'Менделевий',
         'Lname':'Mendelevium',
         'Ename':'Mendelevium',
         'Birth':1955,
         'Eshell':'K2 L8 M18 N32 O31 P8 Q2',
         'Doxi':'+2,+3',
         'Amass':'258.095',
         'density':'Неизвестно',
         'Tmelting':'+825',
         'boil':'Неизвестно' },

"No" : {'num':102,
         'name':'No',
         'Rname':'Нобелий',
         'Lname':'Nobelium',
         'Ename':'Nobelium',
         'Birth':1958,
         'Eshell':'K2 L8 M18 N32 O32 P8 Q2',
         'Doxi':'+2,+3',
         'Amass':'259.100',
         'density':'Неизвестно',
         'Tmelting':'+825',
         'boil':'Неизвестно' },

"Lr" : {'num':103,
         'name':'Lr',
         'Rname':'Лоуренсий',
         'Lname':'Lawrencium',
         'Ename':'Lawrencium',
         'Birth':1961,
         'Eshell':'K2 L8 M18 N32 O32 P8 Q3',
         'Doxi':'+3',
         'Amass':'262',
         'density':'Неизвестно',
         'Tmelting':'+1625',
         'boil':'Неизвестно' },
  
"Rf" : {'num':104,
         'name':'Rf',
         'Rname':'Резерфордий',
         'Lname':'Rutherfordium',
         'Ename':'Rutherfordium',
         'Birth':1967,
         'Eshell':'K2 L8 M18 N32 O32 P10 Q2',
         'Doxi':'+4',
         'Amass':'267',
         'density':'23',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Db" : {'num':104,
         'name':'Db',
         'Rname':'Дубний',
         'Lname':'Dubnium',
         'Ename':'Dubnium',
         'Birth':1970,
         'Eshell':'K2 L8 M18 N32 O32 P11 Q2',
         'Doxi':'+5',
         'Amass':'268',
         'density':'29',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Sg" : {'num':106,
         'name':'Sg',
         'Rname':'Сиборгий',
         'Lname':'Seaborgium',
         'Ename':'Seaborgium',
         'Birth':1974,
         'Eshell':'K2 L8 M18 N32 O32 P12 Q2',
         'Doxi':'Неизвестно',
         'Amass':'271',
         'density':'35',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Bh" : {'num':107,
         'name':'Bh',
         'Rname':'Борий',
         'Lname':'Bohrium',
         'Ename':'Bohrium',
         'Birth':1891,
         'Eshell':'K2 L8 M18 N32 O32 P13 Q2',
         'Doxi':'Неизвестно',
         'Amass':'270',
         'density':'37',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Hs" : {'num':108,
         'name':'Hs',
         'Rname':'Хасий',
         'Lname':'Hassium',
         'Ename':'Hassium',
         'Birth':1984,
         'Eshell':'K2 L8 M18 N32 O32 P14 Q2',
         'Doxi':'Неизвестно',
         'Amass':'269',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Mt" : {'num':109,
         'name':'Mt',
         'Rname':'Мейнтнерий',
         'Lname':'Meitherium',
         'Ename':'Meitherium',
         'Birth':1982,
         'Eshell':'K2 L8 M18 N32 O32 P15 Q2',
         'Doxi':'Неивестно',
         'Amass':'278',
         'density':'37.4',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Ds" : {'num':110,
         'name':'Ds',
         'Rname':'Дармштадтий',
         'Lname':'Darmstadtium',
         'Ename':'Darmstadtium',
         'Birth':1994,
         'Eshell':'K2 L8 M18 N32 O32 P17 Q1',
         'Doxi':'Неизвестно',
         'Amass':'281',
         'density':'34.8',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Rg" : {'num':111,
         'name':'Rg',
         'Rname':'Рентгений',
         'Lname':'Roentgenium',
         'Ename':'Roentgenium',
         'Birth':1994,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q1',
         'Doxi':'Неизвестно',
         'Amass':'281',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Cn" : {'num':112,
         'name':'Cn',
         'Rname':'Коперниций',
         'Lname':'Copernecium',
         'Ename':'Copernecium',
         'Birth':1996,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q2',
         'Doxi':'Неизвестно',
         'Amass':'285',
         'density':'20',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Nh" : {'num':113,
         'name':'Nh',
         'Rname':'Нихоний',
         'Lname':'Nihonium',
         'Ename':'Nihonium',
         'Birth':2004,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q3',
         'Doxi':'Неизвестно',
         'Amass':'284',
         'density':'16',
         'Tmelting':'+425',
         'boil':'+1155' },

"Fl" : {'num':114,
         'name':'Fl',
         'Rname':'Флеровий',
         'Lname':'Flerovium',
         'Ename':'Flerovium',
         'Birth':1999,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q4',
         'Doxi':'Неизвестно',
         'Amass':'289',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Mc" : {'num':115,
         'name':'Mc',
         'Rname':'Московий',
         'Lname':'Moscovium',
         'Ename':'Moscovium',
         'Birth':2004,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q5',
         'Doxi':'Неизвестно',
         'Amass':'289',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Lv" : {'num':116,
         'name':'Lv',
         'Rname':'Ливерморий',
         'Lname':'Livermorium',
         'Ename':'Livermorium',
         'Birth':2000,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q6',
         'Doxi':'Неизвестно',
         'Amass':'292',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Ts" : {'num':117,
         'name':'Ts',
         'Rname':'Теннесин',
         'Lname':'Tennessine',
         'Ename':'Tennessine',
         'Birth':2010,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q7',
         'Doxi':'Неизвестно',
         'Amass':'294',
         'density':'Неизвестно',
         'Tmelting':'Неизвестно',
         'boil':'Неизвестно' },

"Og" : {'num':118,
         'name':'Og',
         'Rname':'Оганнесон',
         'Lname':'Oganesson',
         'Ename':'Oganesson',
         'Birth':2006,
         'Eshell':'K2 L8 M18 N32 O32 P18 Q8',
         'Doxi':'Неизвестно',
         'Amass':'294',
         'density':'5',
         'Tmelting':'Неизвестно',
         'boil':'+95' },

}
